### ISSUE TITLE
Shortcode for Youtube

### ISSUE THREAD

**Issue by integrationtfo** [darmentrout/ableplayer-for-wp#1]
Hello,

I try to use the shortcode for a Youtube link but it doesn't display, I know it accepts multiple file extensions but not sure if Youtube works with it. Do you have an example link by any chance ?

Thank you !

**Comment by darmentrout** [comment]
The plugin does not currently work with YouTube videos. AblePlayer itself provides support but this plugin expects the paths/urls of files, not YT video ids. It does not (currently) have functions to add the parameters necessary for YouTube playback.
